src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="room", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @Assert\Length(max=4096)
     */
    private $private;

    /**
     * @Assert\Length(max=4096)
     */
    private $nbSeats;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Seat", mappedBy="room_id", cascade={"persist", "remove"})
     */
    private $seats;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Game", inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $game;


    public function __construct()
    {
        $this->seats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getPrivate(): ?bool
    {
        return $this->private;
    }

    public function setPrivate(?bool $private): self
    {
        $this->private = $private;

        return $this;
    }

    public function getNbseats()
    {
        return $this->nbSeats;
    }

    public function setNbseats(?int $nbSeats): self
    {
        $this->nbSeats = $nbSeats;

        return $this;
    }

    /**
     * @return Collection|Seat[]
     */
    public function getSeats(): Collection
    {
        return $this->seats;
    }

    public function addSeat(Seat $seat): self
    {
        if (!$this->seats->contains($seat)) {
            $this->seats[] = $seat;
            $seat->setRoomId($this);
        }

        return $this;
    }

    public function removeSeat(Seat $seat): self
    {
        if ($this->seats->contains($seat)) {
            $this->seats->removeElement($seat);
            // set the owning side to null (unless already changed)
            if ($seat->getRoomId() === $this) {
                $seat->setRoomId(null);
            }
        }

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;

use App\Service\GameService;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Translation\TranslatorInterface;

class RoomType extends AbstractType
{
    public function __construct(TranslatorInterface $translator, GameService $GameService)
    {
        $this->tr = $translator;
        $this->gameRep = $GameService;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder            
            ->add('name', TextType::class, ['label' => $this->tr->trans('Name'), 'attr'=>['placeholder'=>$this->tr->trans('Name')]])
            ->add("game", ChoiceType::class, ['label' => $this->tr->trans("Game"), "choices" => $this->getChoices('games'), 'attr'=>["class"=>"select_game"]])
            ->add('nbSeats', ChoiceType::class, ['label' => $this->tr->trans('Number of seats'), 'choices' => $this->getChoices('nbSeats') ])
            ->add('private', CheckboxType::class, ['required' => false, 'label' => $this->tr->trans('Private'), 'attr'=>['placeholder'=>$this->tr->trans('Private'), 'class'=>'check_room_private', 'false-value'=>'0', 'value'=>'1']])
            ->add('password', PasswordType::class, ['required' => false, 'empty_data' => '', 'label' => $this->tr->trans('Password'), 'attr'=>['placeholder'=>$this->tr->trans('Password')]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }

    private function getChoices($type){
        switch($type){
            case 'nbSeats':
                return ['2 (minimum)'=>2, '3'=>3, '4'=>4, '5'=>5, '6'=>6, '7'=>7, '8 (Maximum)'=>8];
                break;
            case 'games':
                $games = $this->gameRep->findBy(["online"=>1]);
                $return = [];
                $return[$this->tr->trans("Choose a game")] = 0;

                foreach($games as $k=>$v){
                    $return[$v->getName()] = $v;
                }

                return $return;
                break;
        }
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Service\RoomService;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class RoomController extends AbstractController
{
    /**
     * @Route("/room/{id}", name="room")
     */
    public function index($id, RoomService $RoomService)
    {
    	if(!$room = $RoomService->find($id)){

    	}else{
            $room->setNbSeats(sizeof($room->getSeats()));
            
    		return $this->render('room/index.html.twig', [
    		    'controller_name' => 'RoomController',
    		    'room' => $room
    		]);
    	}
        
    }

    /**
     * @Route("/room/list/{online}", name="roomlist")
     */
    public function list($online, RoomService $RoomService)
    {
    	$list = ($online === '1') ? $RoomService->findBy(["status"=>1]) : $RoomService->findAll();	
    	$nbRoom = sizeof($list);

        foreach ($list as $k => $room) {
            $list[$k]->getGame()->setTextRules(json_encode($room->getGame()->getRule()->getRules()));
        }

        return $this->render('room/list.html.twig', [
            'controller_name' => 'RoomController',
            'roomList' => $list,
            'nbRoom' => $nbRoom
        ]);
    }
}

templates/room/form_create.html.twig
{% extends 'modal_tpl.html.twig' %}

{% block modal_title %}
	{{ 'Create your room'|trans }}
{% endblock %}

{% block modal_body %}
	{% form_theme room_form 'bootstrap_4_layout.html.twig' %}
	{% if room_form_error != '' %}
	    <div class="alert alert-danger">{{ room_form_error }}</div>
	{% endif %}

	{{ form_start(room_form, {'attr':{'class':'center_form'}}) }}
	    <div class="form-group">
            {{ form_label(room_form.name) }}
            {{ form_errors(room_form.name) }}
            {{ form_widget(room_form.name) }}
            {{ form_help(room_form.name) }}
        </div>

        <div class="form-group">
            {{ form_label(room_form.game) }}
            {{ form_errors(room_form.game) }}
            {{ form_widget(room_form.game) }}
            {{ form_help(room_form.game) }}
        </div>

        <div class="form-group">
            {{ form_label(room_form.nbSeats) }}
            {{ form_errors(room_form.nbSeats) }}
            {{ form_widget(room_form.nbSeats) }}
            {{ form_help(room_form.nbSeats) }}
        </div>

        <div class="form-group">
            {{ form_label(room_form.private) }}
            {{ form_errors(room_form.private) }}
            {{ form_widget(room_form.private) }}
            {{ form_help(room_form.private) }}
        </div>

        <div class="form-group">
            {{ form_label(room_form.password) }}
            {{ form_errors(room_form.password) }}
            {{ form_widget(room_form.password, {'attr': {'disabled': 'disabled'}}) }}
            {{ form_help(room_form.password) }}
        </div>

	    <button class="btn btn-lg btn-primary" type="submit">{{ 'Create!'|trans }}</button>
	{{ form_end(room_form) }} 
{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block header %}{% endblock %}

{% block body %}
	
	<div class="row no-gutters h-100">
		<div id="cont_alert" class="alert alert-primary w-75" style="position: absolute; right: 0px; margin: 0px; z-index:999; text-align: right; display: block;"><ul></ul></div>

		<input type="hidden" id="hid_seat_tpl" value="{{ asset('room/seats.html.twig') }}" />
		<input type="hidden" id="hid_room_id" value="{{ room.getId() }}" />
		<input type="hidden" id="hid_nb_seats" value="{{ room.getNbSeats() }}" />
		<input type="hidden" id="hid_player_id" value="{{ app.getUser().getId() }}" />
		<input type="hidden" id="hid_player_resource" value="" />

		<div id="cont_seats" class="col col-3 h-100 bg-primary">
			<ul id="cont_seats_list" class="no-gutters w-100">
				{% for seat in room.getSeats() %}
					<li class="font-weight-bold bg-light text-dark seat_{{ seat.getPosition() }}">{{ "Seat"|trans }}: <span id="cont_seat_position_{{ seat.getPosition() }}" class="cont_seat_position seat_{{ seat.getPosition() }}">{{ seat.getPosition() }}</span></li>
					<li class="seat_user font-weight-bold bg-light text-dark seat_{{ seat.getPosition() }}">
						{{ "Player"|trans }}: <span id="cont_seat_playername_{{ seat.getPosition() }}" class="cont_seat_playername">{{ "Waiting for player"|trans }}</span>
						<input type="hidden" id="hid_player_data_{{ seat.getPosition() }}" class="hid_player_data" data-playerid="" data-playername="" data-resource="">					
				{% endfor %}
			</ul>
		</div>
		<div id="board" class="col col-9 h-100 bg-secondary"></div>	
	</div>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('https://code.jquery.com/jquery-3.2.1.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/p5/p5.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/p5/addons/p5.dom.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/sketches/tools.js') }}"></script>

	<script src="{{ asset('bundles/goswebsocket/js/vendor/autobahn.min.js') }}"></script>
	<script src="{{ asset('bundles/goswebsocket/js/gos_web_socket_client.js') }}"></script>

	
	<script type="text/javascript" src="{{ asset('js/sketches/checkers/checkers.js?9898') }}"></script>

	{#<script type="text/javascript" src="{{ asset('js/sketches/' ~ room.getGame().getCode() ~ '/' ~ room.getGame().getCode() ~ '.js?9898') }}"></script>#}

	<!-- <script type="text/javascript">

		function loadPlayerData(data){
			var obj = JSON.parse(data);

			console.log(obj);			
			$("#cont_seats_list").empty();
			$.each(obj, function(){
				var content = '<li style="list-style-type: none;" class="font-weight-bold">Seat: '+this.position+'</li><li style="list-style-type: none;" class="seat_user font-weight-bold">Player: '+this.name+'<input type="hidden" class="hid_player_data" data-playerid="'+this.id+'" data-playername="'+this.name+'"></li>';

				$("#cont_seats_list").append(content);

			});
		}

		$(document).ready(function(){
			var webSocket = WS.connect("ws://127.0.0.1:8080");

			webSocket.on("socket/connect", function (session) {
			    //session is an Autobahn JS WAMP session.

			    console.log("Successfully Connected!");

			    session.subscribe("channel/room/{{ room.getId() }}", function (uri, payload) {
			    	console.log("Received message from ", uri);
		            console.log("Received message", payload.msg);

		            //loadPlayerData(payload.msg);
		        });

			    /*var loadPlayersMsg = {type: "api_instruction", msg: "loadUserList"};
		        session.publish("channel/room/{{ room.getId() }}", loadPlayersMsg);*/

			    /*$("#chat_send").keypress(function(e){
			    	if(e.which == 13){
			    		e.preventDefault();
			    		var message = $("#chat_send").val();
			    		console.log("Send message: ", message);

			    		session.publish("channel/room/{{ room.getId() }}", message);
			    	}
			    	

			    });*/
			});

			webSocket.on("socket/disconnect", function (error) {
			    //error provides us with some insight into the disconnection: error.reason and error.code

			    console.log("Disconnected for " + error.reason + " with code " + error.code);
			});
		});
	</script>-->
{% endblock %}

templates/room/list.html.twig
{% for room in roomList %}
	<div class="row room_list_row">
		<div class="col">
			<div class="row">
				<div class="d-flex container-fluid">
					<div class="p-2 mr-auto">
						<strong>{{ room.name }}</strong>
					</div>
					<div class="p-2">
						({{ room.userId.getUsername() }})
					</div>					 
				</div>
			</div>
			<div class="row">
				<div class="d-flex justify-content-between container-fluid">
					<div class="p-2">
						<strong>{{ room.getGame().getCode()|trans }}</strong>
					</div>
					<div class="p-2">
						{{ "Rules: "|trans }} {{ room.getGame().getTextRules() }}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="d-flex justify-content-between container-fluid">
					{% for seat in room.getSeats() %}
						<div class="p-2 room_seats">
							{% if seat.getUserId() is not null %}
								{{ seat.getUserId().getUsername() }}
							{% else %}
								{% if room.userId.getId() != app.user.getId() %}
									<a class="get_seat" data-seatid="{{ seat.getId() }}" data-seatposition="{{ seat.getPosition() }}" data-userid="{{ app.user.getId() }}" href="#">{{ "Sit here"|trans }}</a>
								{% else %}
									{{ "Waiting for player" }}
								{% endif %}
							{% endif %}
						</div>	
					{% endfor %}					 
				</div>
			</div>			
		</div>
	</div>
{% endfor %}
<input type="hidden" id="hid_info_nbroom" value="{{ nbRoom }}" />

templates/room/seats.html.twig
<h1 class="h4 text-center">{{ room.getName() }} tt</h1>
<input type="hidden" id="hid_nbseats" value="{{ room.nbSeats }}" />
{% for seat in room.getSeats() %}
	<div class="row no-gutters w-100 bg-light text-dark" style="margin-bottom: 10px;">
		<ul id="ul_player_list" class="no-gutters">
			<li class="font-weight-bold">{{ "Seat"|trans }}: {{ seat.getPosition() }}</li>
			{% if seat.getUserId() is not null %}
				<li class="seat_user font-weight-bold">
					{{ "Player"|trans }}: {{ seat.getUserId().getUsername() }}
					<input type="hidden" class="hid_player_data" data-playerid="{{ seat.getUserId().getId() }}" data-playername="{{ seat.getUserId().getUsername() }}">
				</li>
			{% else %}
				<li class="font-weight-bold">{{ "Waiting for player"|trans }}</li>
			{% endif %}
		</ul>
	</div>
{% endfor %}

templates/room/testp5.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block header %}{% endblock %}

{% block body %}
	<div class="row no-gutters h-100">
		<div class="col col-3 h-100 bg-primary">
			<h1 class="h4 text-center">{{ room.getName() }}</h1>
			{{ dump(room.getSeats()|length) }}
			{% for seat in room.getSeats() %}
				<div class="row no-gutters w-100 bg-light text-dark" style="margin-bottom: 10px;">
					<ul class="no-gutters">
						<li class="font-weight-bold">{{ "Seat"|trans }}: {{ seat.getPosition() }}</li>
						{% if seat.getUserId() is not null %}
							<li class="font-weight-bold">{{ "Player"|trans }}: {{ seat.getUserId().getUsername() }}</li>
						{% endif %}
					</ul>
				</div>
			{% endfor %}
		</div>
		<div id="board" class="col col-9 h-100 bg-secondary">
			
		</div>	
	</div>
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('https://code.jquery.com/jquery-3.2.1.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/p5/p5.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/p5/addons/p5.dom.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/sketches/tools.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/sketches/checkers/test.js') }}"></script>
{% endblock %}